#使用mac编译
name: Build OpenWrt on mac
on: 
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-12
    steps:
    - name: 查看mac
      run: |
        system_profiler SPHardwareDataType
        xcodebuild -version
