#使用mac编译
name: Build OpenWrt on mac
on: 
  repository_dispatch:
  workflow_dispatch:
env:
  #REPO_URL: https://github.com/coolsnowwolf/lede
  #REPO_BRANCH: master
  FEEDS_CONF: feeds/feeds.conf.default
  CONFIG_FILE: config/lede_x86.config
jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: 查看mac
      run: |
        system_profiler SPHardwareDataType
        xcodebuild -version
        df -lh
        make -v
    - name: 安装 Homebrew
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - name: 使用 Homebrew 安装工具链、依赖与基础软件包
      run: |
        #brew unlink awk
        brew update
        brew upgrade
        brew install coreutils diffutils findutils gawk gnu-getopt gnu-tar grep make ncurses pkg-config wget quilt xz
        #brew install coreutils diffutils findutils gawk gnu-getopt gnu-tar grep ncurses pkg-config wget quilt xz
        brew install gcc@12
        #brew install mkisofs  #找不到安装
        #sudo ln -s /usr/bin/genisoimage /usr/bin/mkisofs #不允许操作
        make -v
    - name: 升级make
      run: |
        wget http://ftp.gnu.org/gnu/make/make-4.2.1.tar.gz
        tar xf make-4.2.1.tar.gz
        cd make-4.2.1/
        ./configure
        make
        make install
        export PATH="/usr/local/bin:$PATH"
        make -v
    - name: 输入以下命令，添加到系统环境变量中
      run: |
        echo 'export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"' >> ~/.bashrc
        echo 'export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"' >> ~/.bashrc
        #echo 'export PATH="/usr/bin/mkisofs:$PATH"' >> ~/.bashrc
        cat ~/.bashrc
        make -v
    - name: 重新加载shell 启动文件
      run: |
        source ~/.bashrc
        bash

    - name: 创建大小写敏感的磁盘镜像
      run: |
        hdiutil create -size 50g -type SPARSE -fs "Case-sensitive HFS+" -volname OpenWrt OpenWrt.sparseimage
        hdiutil attach OpenWrt.sparseimage

    - name: 下载源代码
      run: |
        cd /Volumes/OpenWrt
        git clone https://github.com/coolsnowwolf/lede
        
    - name: 更新和安装feeds
      run: |
        #[ -e $FEEDS_CONF ] && mv $FEEDS_CONF /Volumes/OpenWrt/lede/feeds.conf.default
        cd /Volumes/OpenWrt/lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: 配置编译选项
      run: |
        cd /Volumes/OpenWrt/lede
        make defconfig
        #cd ../../../
        #[ -e $CONFIG_FILE ] && mv $CONFIG_FILE /Volumes/OpenWrt/lede/.config
        #[ -e $CONFIG_FILE ] && cp -v $CONFIG_FILE /Volumes/OpenWrt/lede/.config
    - name: 下载 dl 库，编译固件
      run: |
        bash
        cd /Volumes/OpenWrt/lede
        make download -j8
        make -j$(nproc) ||  make -j1 V=s
    - name: 编译结束
      run: |
        echo "done"
